const FIELDS = [
  {name: "Biologie", value: "Biologie"},
  {name: "Chimie", value: "Chimie"},
  {name: "Physique", value: "Physique"},
  {name: "Mathématiques", value: "Mathématiques"},
  {name: "Informatique", value: "Informatique"},
  {name: "Langues étrangères appliquées (LEA)", value: "Langues étrangères appliquées (LEA)"},
  {name: "Lettres modernes", value: "Lettres modernes"},
  {name: "Sciences de l'éducation", value: "Sciences de l'éducation"},
  {name: "Droit", value: "Droit"},
  {name: "Science politique", value: "Science politique"},
  {name: "Sciences économiques", value: "Sciences économiques"},
  {name: "Gestion", value: "Gestion"},
  {name: "Médecine", value: "Médecine"},
  {name: "Pharmacie", value: "Pharmacie"},
  {name: "Odontostomatologie", value: "Odontostomatologie"},
  {name: "Sciences de l'environnement", value: "Sciences de l'environnement"},
  {name: "Géographie", value: "Géographie"},
  {name: "Sociologie", value: "Sociologie"},
  {name: "Anthropologie", value: "Anthropologie"},
  {name: "Histoire", value: "Histoire"},
  {name: "Archéologie", value: "Archéologie"},
  {name: "Philosophie", value: "Philosophie"},
  {name: "Psychologie", value: "Psychologie"},
  {name: "Muséologie", value: "Muséologie"},
  {name: "Sciences et techniques de la communication", value: "Sciences et techniques de la communication"},
];
export default FIELDS;
